### ISSUE TITLE
Form contacto

### ISSUE THREAD

**Issue by NicoGonzalez94** [pablogonza37/ProyectoFinalRollingCode#56]
## Proceso

1. Ingrese a la pagina.
2. Quise hacer una consulta.

## Resultado esperado

• Que no se permita colocar numeros ni signos en el nombre del usuario.

## Resultado actual

• Se permite colocar numero y signos en el nombre.

## Captura

![image](https://github.com/pablogonza37/ProyectoFinalRollingCode/assets/166792979/68781c1f-2ed9-48fb-b691-fe420c89f3e5)
![image](https://github.com/pablogonza37/ProyectoFinalRollingCode/assets/166792979/77baefb8-cb97-4077-8c2a-816d60f73576)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by pablogonza37** [comment]
agregamos la validación para evitar poder ingresar números o símbolos en el input nombre
